-- Migration 0014: Person digest
--
-- Adds AI-generated digest fields to the people table.
-- The digest is a synthesised narrative of who this person is and what they care about,
-- drawn from all their evidence across every project in the org.
-- Generated by the synthesise-person Inngest function; refreshed on demand or after
-- each ingest that adds new evidence mentioning this person.

alter table people
  add column if not exists digest text,
  add column if not exists digest_updated_at timestamptz;

comment on column people.digest is
  'AI-synthesised narrative: who this person is, their role, key perspectives, and what they want. '
  'Generated from all linked evidence_entities records across all projects.';

comment on column people.digest_updated_at is
  'When the digest was last generated. Null means it has never been generated.';
