-- Migration 0015: Frame draft columns on projects
--
-- Adds AI-generated frame draft storage. The draft is written by the
-- draft-frame Inngest function after the first ingest on a project if
-- projects.frame is null. It does NOT overwrite the live frame — that
-- stays under Jimmy's control. The UI surfaces the draft with an accept/
-- discard action.
--
-- columns:
--   frame_draft            jsonb   — structured draft produced by Claude
--                                    shape: { problem, hypothesis, buyers, research_areas[] }
--   frame_draft_generated_at timestamptz — when the draft was last written

alter table projects
  add column if not exists frame_draft            jsonb,
  add column if not exists frame_draft_generated_at timestamptz;

comment on column projects.frame_draft is
  'AI-proposed project frame draft. Shape: { problem: string, hypothesis: string, buyers: string, research_areas: string[] }. Null until draft-frame function fires. Does not overwrite the live frame field.';

comment on column projects.frame_draft_generated_at is
  'When the current frame_draft was last generated by the draft-frame Inngest function.';
