-- Migration 0016: Company digest columns
--
-- Adds AI-synthesised digest storage to the companies table.
-- The synthesise-company Inngest function writes here after entity extraction
-- accumulates enough evidence linked to a company across all projects.
--
-- columns:
--   digest               text       — prose narrative (3–5 paragraphs)
--   digest_updated_at    timestamptz — when the digest was last written

alter table companies
  add column if not exists digest            text,
  add column if not exists digest_updated_at timestamptz;

comment on column companies.digest is
  'AI-synthesised narrative covering: who they are, collective themes from all people at this company, cross-project involvement, and overall relationship signal. Written by synthesise-company Inngest function.';

comment on column companies.digest_updated_at is
  'When the current digest was last generated by the synthesise-company function.';
